# -*- coding: mbcs -*-
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
mdb.Model(name='Model')
mdb.models['Model'].ConstrainedSketch(name='__profile__', sheetSize=200)
mdb.models['Model'].sketches['__profile__'].Line(point1=(-30, 100), point2=(
    -30, -100))
mdb.models['Model'].sketches['__profile__'].Line(point1=(-30, -100), point2=(
    30, -100))
mdb.models['Model'].sketches['__profile__'].Line(point1=(30, -100), point2=(30, 
    -80))
mdb.models['Model'].sketches['__profile__'].Line(point1=(30, -80), point2=(25, 
    -80))
mdb.models['Model'].sketches['__profile__'].Line(point1=(25, -80), point2=(25, 
    -95))
mdb.models['Model'].sketches['__profile__'].Line(point1=(25, -95), point2=(-25, 
    -95))
mdb.models['Model'].sketches['__profile__'].Line(point1=(-25, -95), point2=(
    -25, 95))
mdb.models['Model'].sketches['__profile__'].Line(point1=(-25, 95), point2=(25, 
    95))
mdb.models['Model'].sketches['__profile__'].Line(point1=(25, 95), point2=(25, 
    80))
mdb.models['Model'].sketches['__profile__'].Line(point1=(25, 80), point2=(30, 
    80))
mdb.models['Model'].sketches['__profile__'].Line(point1=(30, 80), point2=(30, 
    100))
mdb.models['Model'].sketches['__profile__'].Line(point1=(30, 100), point2=(-30, 
    100))
mdb.models['Model'].Part(dimensionality=THREE_D, name='beam', type=
    DEFORMABLE_BODY)
mdb.models['Model'].parts['beam'].BaseSolidExtrude(depth=1200, sketch=
    mdb.models['Model'].sketches['__profile__'])
del mdb.models['Model'].sketches['__profile__']
mdb.models['Model'].ConstrainedSketch(gridSpacing=60.84, name='__profile__', 
    sheetSize=2400, transform=
    mdb.models['Model'].parts['beam'].MakeSketchTransform(
    sketchPlane=mdb.models['Model'].parts['beam'].faces[10], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model'].parts['beam'].edges[33], 
    sketchOrientation=RIGHT, origin=(-30.0, 0.0, 600.0)))
mdb.models['Model'].parts['beam'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['Model'].sketches['__profile__'])
mdb.models['Model'].sketches['__profile__'].sketchOptions.setValues(gridOrigin=
    (-600, 100))
mdb.models['Model'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    -50, -20), point1=(-43, -20))
mdb.models['Model'].sketches['__profile__'].linearPattern(angle1=0.0, angle2=
    270.0, geomList=(mdb.models['Model'].sketches['__profile__'].geometry[6], )
    , number1=4, number2=3, spacing1=100, spacing2=50, vertexList=())
mdb.models['Model'].parts['beam'].CutExtrude(flipExtrudeDirection=OFF, sketch=
    mdb.models['Model'].sketches['__profile__'], sketchOrientation=RIGHT, 
    sketchPlane=mdb.models['Model'].parts['beam'].faces[10], sketchPlaneSide=
    SIDE1, sketchUpEdge=mdb.models['Model'].parts['beam'].edges[33])
del mdb.models['Model'].sketches['__profile__']
mdb.models['Model'].ConstrainedSketch(name='__profile__', sheetSize=200)
mdb.models['Model'].sketches['__profile__'].Line(point1=(-30, 100), point2=(
    -30, -100))
mdb.models['Model'].sketches['__profile__'].Line(point1=(-30, -100), point2=(
    30, -100))
mdb.models['Model'].sketches['__profile__'].Line(point1=(30, -100), point2=(30, 
    -80))
mdb.models['Model'].sketches['__profile__'].Line(point1=(30, -80), point2=(25, 
    -80))
mdb.models['Model'].sketches['__profile__'].Line(point1=(25, -80), point2=(25, 
    -95))
mdb.models['Model'].sketches['__profile__'].Line(point1=(25, -95), point2=(-25, 
    -95))
mdb.models['Model'].sketches['__profile__'].Line(point1=(-25, -95), point2=(
    -25, 95))
mdb.models['Model'].sketches['__profile__'].Line(point1=(-25, 95), point2=(25, 
    95))
mdb.models['Model'].sketches['__profile__'].Line(point1=(25, 95), point2=(25, 
    80))
mdb.models['Model'].sketches['__profile__'].Line(point1=(25, 80), point2=(30, 
    80))
mdb.models['Model'].sketches['__profile__'].Line(point1=(30, 80), point2=(30, 
    100))
mdb.models['Model'].sketches['__profile__'].Line(point1=(30, 100), point2=(-30, 
    100))
mdb.models['Model'].Part(dimensionality=THREE_D, name='column', type=
    DEFORMABLE_BODY)
mdb.models['Model'].parts['column'].BaseSolidExtrude(depth=890, sketch=
    mdb.models['Model'].sketches['__profile__'])
del mdb.models['Model'].sketches['__profile__']
mdb.models['Model'].ConstrainedSketch(gridSpacing=60.84, name='__profile__', 
    sheetSize=1780, transform=
    mdb.models['Model'].parts['column'].MakeSketchTransform(
    sketchPlane=mdb.models['Model'].parts['column'].faces[10], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model'].parts['column'].edges[33], 
    sketchOrientation=RIGHT, origin=(-30.0, 0.0, 445.0)))
mdb.models['Model'].parts['column'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['Model'].sketches['__profile__'])
mdb.models['Model'].sketches['__profile__'].sketchOptions.setValues(gridOrigin=
    (-445, 100))
mdb.models['Model'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    -50, -20), point1=(-43, -20))
mdb.models['Model'].sketches['__profile__'].linearPattern(angle1=0.0, angle2=
    270.0, geomList=(mdb.models['Model'].sketches['__profile__'].geometry[6], )
    , number1=3, number2=3, spacing1=50, spacing2=50, vertexList=())
mdb.models['Model'].parts['column'].CutExtrude(flipExtrudeDirection=OFF, 
    sketch=mdb.models['Model'].sketches['__profile__'], sketchOrientation=RIGHT
    , sketchPlane=mdb.models['Model'].parts['column'].faces[10], 
    sketchPlaneSide=SIDE1, sketchUpEdge=
    mdb.models['Model'].parts['column'].edges[33])
del mdb.models['Model'].sketches['__profile__']
#* *** Error: File open failed (utl_File: CreateFile in OpenWrite)
#* error: The process cannot access the file because it is being used by 
#* another process.
#* 
#* file: C:\Users\User\OneDrive\RUB\Master\Second Semester\Applied 
#* FEM\Abaqus\AbaqusScriptingRubProject\output\SteelConnection.cae
